baseurl = "https://louismeunier.net/"
title = "louis meunier"
author = "louis meunier"
canonifyurls = true
languagecode = "en-us"


enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "louis meunier"
  faviconfile = "images/favicon.svg"
  highlightjs = true
  highlightjslanguages = ["r", "python", "javascript", "typescript", "java"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
# [[menu.primary]]
#     name = "About"
#     url = "/about/"
#     weight = 2
[[menu.primary]]
    name = "Github"
    url = "https://github.com/louismeunier"
    weight = 4
[[menu.primary]]
    name = "Linkedin"
    url = "https://linkedin.louismeunier.net"
    weight = 5
[[menu.primary]]
    name = "Projects"
    url = "/projects"
    weight = 2
[[menu.primary]]
    name = "Notes"
    url = "https://notes.louismeunier.net"
    weight = 3